### ISSUE TITLE
rendering-issue with navs

### ISSUE THREAD

**Issue by kusma** [pouetnet/pouet2.0#80]
![image](https://user-images.githubusercontent.com/47073/36988876-3ee64d1a-20a0-11e8-8b50-494b7d6eb3f0.png)

This happens when the browser-windows is more narrow than the page, because the body-tag doesn't fill the whole page. Which in turn is due to general CSS suckiness.

Adding the following CSS fixes the problem for me:
```css
body {
    position: absolute;
    min-width: 100%;
}
#logo img {
    max-width: 100%;
}
```

But sadly, I can't figure out how to send a PR for this, as the CSS doesn't seem to be part of this repo, and I can't figure out where it lives...
